import { makeRequest, printRequestSummary } from '/app/test-utils.mjs';

await makeRequest('GET', '/health');
await makeRequest('GET', '/connection/query-callback');
await makeRequest('GET', '/connection/query-params?key=test_key_1');
await makeRequest('GET', '/connection/query-options');
await makeRequest('GET', '/connection/query-stream');
await makeRequest('GET', '/connection/multi-statement');
await makeRequest('GET', '/pool/query');
await makeRequest('GET', '/pool/get-connection');
await makeRequest('POST', '/transaction/commit');
await makeRequest('POST', '/transaction/rollback');
await makeRequest('POST', '/test/transaction-with-options');
await makeRequest('POST', '/crud/insert', { body: { key: 'crud_test_insert', value: 'test_value' } });
await makeRequest('PUT', '/crud/update', { body: { key: 'test_key_1', value: 'updated_value' } });
await makeRequest('DELETE', '/crud/delete', { body: { key: 'crud_test_insert' } });
await makeRequest('GET', '/advanced/join');
await makeRequest('GET', '/advanced/aggregate');
await makeRequest('GET', '/advanced/subquery');
await makeRequest('GET', '/advanced/prepared');
await makeRequest('GET', '/lifecycle/ping');
await makeRequest('GET', '/lifecycle/end-and-reconnect');
await makeRequest('POST', '/lifecycle/change-user');
await makeRequest('GET', '/lifecycle/pause-resume');
await makeRequest('GET', '/pool/end-and-recreate');
await makeRequest('GET', '/test/pool-events');
await makeRequest('GET', '/test/pool-namespace-query');
await makeRequest('GET', '/events/connect');
await makeRequest('GET', '/stream/query-stream-method');
await makeRequest('GET', '/test/connection-destroy');
await makeRequest('GET', '/test/query-object-reuse');
await makeRequest('GET', '/test/pool-namespace-query-stream');
await makeRequest('POST', '/test/pool-connection-transaction-options');
await makeRequest('GET', '/test/pool-getconnection-query-with-internal-callback');
await makeRequest('GET', '/test/pool-namespace-query-with-internal-callback');
await makeRequest('GET', '/knex/basic-select');
await makeRequest('GET', '/knex/raw-query');

printRequestSummary();
