import { makeRequest, printRequestSummary } from '/app/test-utils.mjs';

await makeRequest('GET', '/health');
await makeRequest('GET', '/test/get');
await makeRequest('POST', '/test/set', { body: { key: 'test:newkey', value: 'newvalue' } });
await makeRequest('POST', '/test/del', { body: { key: 'test:newkey' } });
await makeRequest('POST', '/test/exists', { body: { key: 'test:key1' } });
await makeRequest('POST', '/test/expire', { body: { key: 'test:key1', seconds: 100 } });
await makeRequest('POST', '/test/ttl', { body: { key: 'test:key1' } });
await makeRequest('GET', '/test/incr');
await makeRequest('GET', '/test/decr');
await makeRequest('GET', '/test/mget');
await makeRequest('POST', '/test/mset');
await makeRequest('GET', '/test/hget');
await makeRequest('POST', '/test/hset', { body: { key: 'test:user:2', field: 'name', value: 'Jane Doe' } });
await makeRequest('GET', '/test/hgetall');
await makeRequest('POST', '/test/hdel', { body: { key: 'test:user:1', field: 'age' } });
await makeRequest('POST', '/test/lpush', { body: { key: 'test:list', value: 'item0' } });
await makeRequest('POST', '/test/rpush', { body: { key: 'test:list', value: 'item4' } });
await makeRequest('POST', '/test/lpop', { body: { key: 'test:list' } });
await makeRequest('POST', '/test/rpop', { body: { key: 'test:list' } });
await makeRequest('GET', '/test/lrange');
await makeRequest('POST', '/test/llen', { body: { key: 'test:list' } });
await makeRequest('POST', '/test/sadd', { body: { key: 'test:set', member: 'member4' } });
await makeRequest('POST', '/test/srem', { body: { key: 'test:set', member: 'member4' } });
await makeRequest('GET', '/test/smembers');
await makeRequest('POST', '/test/sismember', { body: { key: 'test:set', member: 'member1' } });
await makeRequest('POST', '/test/zadd', { body: { key: 'test:zset', score: 4, member: 'score4' } });
await makeRequest('GET', '/test/zrange');
await makeRequest('POST', '/test/zrem', { body: { key: 'test:zset', member: 'score4' } });
await makeRequest('POST', '/test/zscore', { body: { key: 'test:zset', member: 'score1' } });
await makeRequest('POST', '/test/keys', { body: { pattern: 'test:*' } });
await makeRequest('POST', '/test/flushdb');
await makeRequest('GET', '/test/ping');
await makeRequest('GET', '/test/pipeline');
await makeRequest('GET', '/test/multi');
await makeRequest('GET', '/test/new-client');
await makeRequest('GET', '/test/getbuffer');
await makeRequest('GET', '/test/mgetbuffer');

printRequestSummary();
