version: '3.8'

services:
  app:
    build:
      context: ../../../../../..
      dockerfile: src/instrumentation/libraries/http/e2e-tests/cjs-http/Dockerfile
      args:
        - CACHEBUST=${CACHEBUST:-1}
        - TUSK_CLI_VERSION=${TUSK_CLI_VERSION:-latest}
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - PORT=3000
    volumes:
      # Mount SDK source for hot reload (this is what package.json expects)
      - ../../../../../..:/sdk:ro
      # Mount .tusk folder to persist traces
      - ./.tusk:/app/.tusk
      # Mount app source for development
      - ./src:/app/src
    working_dir: /app
    # Keep container running without starting the app
    # The CLI will control starting/stopping the app
    command: tail -f /dev/null
